version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  endorse-data-nlp:
    build:
     context: ../endorse-data-nlp
    ports:
      - "3002:3002"
    environment:
      - ELASTIC_SERACH_HOST=elasticsearch
      - ELASTIC_SERACH_USERNAME=
      - ELASTIC_SERACH_PASSWORD=
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - logstash
    command: ["./start.sh"]
    volumes:
      - /data/projects/

  endorse-dashboard:
    build:
      context: ../endorse-dashboard
    ports:
      - "3000:3000"
    environment:
      - NLP_SERVICE_BASE_URL=http://endorse-data-nlp:3002/api/1
    networks:
      - elk
    links:
      - endorse-data-nlp

networks:
  elk:
    driver: bridge

volumes:
  data:
    driver: local